# Site settings
title: Sydney with Qatar Airways

clients:
  - name: Qatar Airways
    logo: qatar.svg
    link: "https://www.qatarairways.com/en-gb/destinations/flights-to-sydney.html?cid=BAGB891400"
  - name: Destination New South Wales
    logo: dnsw.svg
    link: "https://www.visitnsw.com/"

core-se-link: https://www.secretescapes.com/current-sales
description: >
  From wanderlust-inspiring beaches to the bustling sprawl of Australia’s favourite urban escape, New South Wales harbours adventures for all tastes. Visit a land of spectacular foodie delights, famed wine estates, endless beach idylls and fascinating cultures to uncover. Whether it’s kicking back on the white-sand beaches of Jervis Bay or getting lost in the addictive energy of Sydney, explore this enigmatic region from the perspective of true locals.

# file paths
url:     "http://mp.secretescapes.com" # the base hostname & protocol for your site
baseurl: "/qatar-new-south-wales" # the subpath of your site, e.g. /blog/
img:     "/qatar-new-south-wales/_assets/img"
css:     "/qatar-new-south-wales/_assets/css"
js:      "/qatar-new-south-wales/_assets/js"


# Build settings
markdown: kramdown
exclude: [node_modules, gulpfile.js, package.json, package-lock.json, js/script.js]
keep_files: [_assets]
sass:
    sass_dir: css
    style: compressed